from thefuzz import fuzz,process
import random
import skfuzzy
import skfuzzy.membership as mf
import matplotlib.pyplot as plt
import numpy as np

x1 = str("  Rayan Bey ")
x2 = str("  Rayan ")


def fuzzratio(s1,s2):

    fuzzrate = fuzz.ratio(s1,s2)
    return fuzzrate

def partialratio (s1,s2):
    Fuzzpartialrate = fuzz.partial_ratio(s1,s2)
    return Fuzzpartialrate

def tokenratio(s1,s2):
    TokenRate = fuzz.token_sort_ratio(s1,s2)
    return TokenRate

def tokensetratio(s1, s2):
    TokenSetRatio = fuzz.token_set_ratio(s1, s2)
    return TokenSetRatio


x_Fuzzratio = np.arange(0,101,1)
x_Partialratio = np.arange(0,101,1)
x_Tokenratio = np.arange(0,101,1)
x_Tokensetratio = np.arange(0,101,1)
x_Benzerlikratio = np.arange(0,101,1)

FuzzRatio_VLow = mf.trapmf(x_Fuzzratio, [0,0,10,30])
FuzzRatio_MLow = mf.trimf(x_Fuzzratio, [10,30,50])
FuzzRatio_AVE = mf.trimf(x_Fuzzratio, [30,50,70])
FuzzRatio_MHigh = mf.trimf(x_Fuzzratio, [50,70,90])
FuzzRatio_VHigh = mf.trapmf(x_Fuzzratio, [70,90,100,100])

PartialRatio_VLow = mf.trapmf(x_Partialratio, [0,0,10,30])
PartialRatio_MLow = mf.trimf(x_Partialratio, [10,30,50])
PartialRatio_AVE = mf.trimf(x_Partialratio, [30,50,70])
PartialRatio_MHigh = mf.trimf(x_Partialratio, [50,70,90])
PartialRatio_VHigh = mf.trapmf(x_Partialratio, [70,90,100,100])

TokenRatio_VLow = mf.trapmf(x_Tokenratio, [0,0,10,30])
TokenRatio_MLow = mf.trimf(x_Tokenratio, [10,30,50])
TokenRatio_AVE = mf.trimf(x_Tokenratio, [30,50,70])
TokenRatio_MHigh = mf.trimf(x_Tokenratio, [50,70,90])
TokenRatio_VHigh = mf.trapmf(x_Tokenratio, [70,90,100,100])

TokenSetRatio_VLow = mf.trapmf(x_Tokensetratio, [0,0,10,30])
TokenSetRatio_MLow = mf.trimf(x_Tokensetratio, [10,30,50])
TokenSetRatio_AVE = mf.trimf(x_Tokensetratio, [30,50,70])
TokenSetRatio_MHigh = mf.trimf(x_Tokensetratio, [50,70,90])
TokenSetRatio_VHigh = mf.trapmf(x_Tokensetratio, [70,90,100,100])

BenzerlikRatio_VLow = mf.trapmf(x_Benzerlikratio,[0,0,10,30])
BenzerlikRatio_MLow = mf.trimf(x_Benzerlikratio,[10,30,50])
BenzerlikRatio_AVE = mf.trimf(x_Benzerlikratio,[30,50,70])
BenzerlikRatio_MHigh = mf.trimf(x_Benzerlikratio,[50,70,90])
BenzerlikRatio_VHigh = mf.trapmf(x_Benzerlikratio,[70,90,100,100])

ig , (ax0,ax1,ax2,ax3,ax4) = plt.subplots(nrows= 5 ,figsize = (6,10))

ax0.plot(FuzzRatio_VLow , "r", linewidth = 2, label = "Çok Düşük")
ax0.plot(FuzzRatio_MLow , "g", linewidth = 2, label = " Düşük")
ax0.plot(FuzzRatio_AVE, "c", linewidth = 2,label = "Ortalama" )
ax0.plot(FuzzRatio_MHigh , "m", linewidth = 2, label = "Yüksek")
ax0.plot(FuzzRatio_VHigh , "y", linewidth = 2, label = "Çok Yüksek")


ax0.set_title("Fuzz Ratio")
ax0.legend()

ax1.plot(PartialRatio_VLow , "r", linewidth = 2, label = "Çok Düşük")
ax1.plot(PartialRatio_MLow , "g", linewidth = 2, label = " Düşük")
ax1.plot(PartialRatio_AVE, "c", linewidth = 2,label = "Ortalama" )
ax1.plot(PartialRatio_MHigh , "m", linewidth = 2, label = "Yüksek")
ax1.plot(PartialRatio_VHigh , "y", linewidth = 2, label = "Çok Yüksek")

ax1.set_title("Partial Fuzz Ratio")
ax1.legend()

ax2.plot(TokenRatio_VLow , "r", linewidth = 2, label = "Çok Düşük")
ax2.plot(TokenRatio_MLow , "g", linewidth = 2, label = " Düşük")
ax2.plot(TokenRatio_AVE, "c", linewidth = 2,label = "Ortalama" )
ax2.plot(TokenRatio_MHigh , "m", linewidth = 2, label = "Yüksek")
ax2.plot(TokenRatio_VHigh , "y", linewidth = 2, label = "Çok Yüksek")

ax2.set_title("Token Ratio")
ax2.legend()

ax3.plot(TokenSetRatio_VLow , "r", linewidth = 2, label = "Çok Düşük")
ax3.plot(TokenSetRatio_MLow , "g", linewidth = 2, label = " Düşük")
ax3.plot(TokenSetRatio_AVE, "c", linewidth = 2,label = "Ortalama" )
ax3.plot(TokenSetRatio_MHigh , "m", linewidth = 2, label = "Yüksek")
ax3.plot(TokenSetRatio_VHigh , "y", linewidth = 2, label = "Çok Yüksek")

ax3.set_title("Token Set Ratio")
ax3.legend()

ax4.plot(BenzerlikRatio_VLow, "r",linewidth= 2 ,label = "Çok düşük")
ax4.plot(BenzerlikRatio_MLow , "g", linewidth = 2, label = " Düşük")
ax4.plot(BenzerlikRatio_AVE, "c", linewidth = 2,label = "Ortalama" )
ax4.plot(BenzerlikRatio_MHigh , "m", linewidth = 2, label = "Yüksek")
ax4.plot(BenzerlikRatio_VHigh, "y", linewidth = 2 , label ="Çok Yüksek ")

ax4.set_title("Benzerlik")
ax4.legend()

plt.tight_layout()

for ax in (ax0, ax1, ax2,ax3,ax4):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.get_xaxis().tick_bottom()
    ax.get_yaxis().tick_left()

plt.tight_layout()

FuzzRatio_fit_VLow = skfuzzy.interp_membership(x_Fuzzratio,FuzzRatio_VLow,fuzzratio(x1,x2))
FuzzRatio_fit_MLow = skfuzzy.interp_membership(x_Fuzzratio,FuzzRatio_MLow,fuzzratio(x1,x2))
FuzzRatio_fit_AVE = skfuzzy.interp_membership(x_Fuzzratio,FuzzRatio_AVE,fuzzratio(x1,x2))
FuzzRatio_fit_MHigh = skfuzzy.interp_membership(x_Fuzzratio,FuzzRatio_MHigh,fuzzratio(x1,x2))
FuzzRatio_fit_VHigh = skfuzzy.interp_membership(x_Fuzzratio,FuzzRatio_VHigh,fuzzratio(x1,x2))

PartialRatio_fit_VLow = skfuzzy.interp_membership(x_Partialratio,PartialRatio_VLow,partialratio(x1,x2))
PartialRatio_fit_MLow = skfuzzy.interp_membership(x_Partialratio,PartialRatio_MLow,partialratio(x1,x2))
PartialRatio_fit_AVE = skfuzzy.interp_membership(x_Partialratio,PartialRatio_AVE,partialratio(x1,x2))
PartialRatio_fit_MHigh = skfuzzy.interp_membership(x_Partialratio,PartialRatio_MHigh,partialratio(x1,x2))
PartialRatio_fit_VHigh = skfuzzy.interp_membership(x_Partialratio,PartialRatio_VHigh,partialratio(x1,x2))

TokenRatio_fit_VLow = skfuzzy.interp_membership(x_Tokenratio,TokenRatio_VLow,tokenratio(x1,x2))
TokenRatio_fit_MLow = skfuzzy.interp_membership(x_Tokenratio,TokenRatio_MLow,tokenratio(x1,x2))
TokenRatio_fit_AVE = skfuzzy.interp_membership(x_Tokenratio,TokenRatio_AVE,tokenratio(x1,x2))
TokenRatio_fit_MHigh = skfuzzy.interp_membership(x_Tokenratio,TokenRatio_MHigh,tokenratio(x1,x2))
TokenRatio_fit_VHigh = skfuzzy.interp_membership(x_Tokenratio,TokenRatio_VHigh,tokenratio(x1,x2))

TokenSetRatio_fit_VLow = skfuzzy.interp_membership(x_Tokensetratio,TokenSetRatio_VLow,tokensetratio(x1,x2))
TokenSetRatio_fit_MLow = skfuzzy.interp_membership(x_Tokensetratio,TokenSetRatio_MLow,tokensetratio(x1,x2))
TokenSetRatio_fit_AVE = skfuzzy.interp_membership(x_Tokensetratio,TokenSetRatio_AVE,tokensetratio(x1,x2))
TokenSetRatio_fit_MHigh = skfuzzy.interp_membership(x_Tokensetratio,TokenSetRatio_MHigh,tokensetratio(x1,x2))
TokenSetRatio_fit_VHigh = skfuzzy.interp_membership(x_Tokensetratio,TokenSetRatio_VHigh,tokensetratio(x1,x2))

rule1 = np.fmin(FuzzRatio_fit_VHigh ,BenzerlikRatio_VHigh)
rule2 = np.fmax(FuzzRatio_fit_MHigh,BenzerlikRatio_VHigh)
rule3 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule4 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule5 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule6 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule7 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule8 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule9 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule10 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule11 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule12 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule13 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule14 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule15 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule16 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule17 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule18 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule19 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule20 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule21 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule22 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule23 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule24 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule25 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule26 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule27 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule28 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule29 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_AVE,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule30 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule31 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule32 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule33 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MHigh)
rule34 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule35 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule36 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule37 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_AVE)
rule38 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule39 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule40 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule41 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule42 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule43 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule44 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule45 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule46 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule47 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_VHigh)
rule48 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule49 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_AVE)
rule50 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule51 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule52 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_MHigh)
rule53 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_AVE)
rule54 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule55 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule56 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule57 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_AVE)
rule58 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule59 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule60 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule61 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule62 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule63 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule64 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule65 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_AVE)
rule66 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule67 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule68 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule69 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_AVE)
rule70 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule71 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule72 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule73 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule74 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule75 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule76 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule77 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule78 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule79 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule80 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule81 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule82 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule83 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule84 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule85 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule86 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule87 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule88 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule89 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule90 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule91 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MLow)
rule92 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule93 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_MLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule94 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule95 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule96 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule97 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MLow)
rule98 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule99 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule100 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule101 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule102 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule103 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule104 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VLow)),BenzerlikRatio_MLow)
rule105 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule106 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule107 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule108 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule109 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_MLow)
rule110 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule111 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule112 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule113 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule114 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule115 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule116 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule117 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule118 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule119 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule120 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule121 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule122 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MLow)
rule123 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MLow)
rule124 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule125 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule126 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule127 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule128 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule129 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule130 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule131 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule132 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule133 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule134 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule135 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule136 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule137 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule138 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule139 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule140 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule141 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule142 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule143 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MLow),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule144 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule145 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule146 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule147 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule148 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule149 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule150 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule151 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule152 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule153 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule154 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule155 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule156 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule157 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule158 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule159 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule160 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule161 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule162 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule163 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule164 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule165 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule166 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule167 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule168 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_AVE),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule169 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule170 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule171 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_VLow)
rule172 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule173 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule174 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule175 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule176 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule177 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule178 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule179 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule180 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule181 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule182 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule183 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule184 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule185 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule186 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule187 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule188 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule189 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule190 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule191 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule192 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule193 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_MHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)
rule194 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule195 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule196 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule197 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_AVE)
rule198 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule199 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule200 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MLow)),BenzerlikRatio_VLow)
rule201 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_AVE)),BenzerlikRatio_MLow)
rule202 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MLow)
rule203 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MLow,TokenSetRatio_fit_VHigh)),BenzerlikRatio_AVE)
rule204 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule205 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule206 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule207 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule208 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_AVE,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule209 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule210 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule211 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule212 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule213 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_MHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_MHigh)
rule214 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VLow)),BenzerlikRatio_VLow)
rule215 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MLow)),BenzerlikRatio_MLow)
rule216 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_AVE)),BenzerlikRatio_AVE)
rule217 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_MHigh)),BenzerlikRatio_MHigh)
rule218 = np.fmax(np.fmax(np.fmax(FuzzRatio_fit_VLow,PartialRatio_fit_VHigh),np.fmax(TokenRatio_fit_VHigh,TokenSetRatio_fit_VHigh)),BenzerlikRatio_VHigh)

#Vhigh

binding_rule_Vhigh1 = np.fmin(rule1,rule2)
binding_rule_Vhigh2 = np.fmin(rule3,rule4)
binding_rule_Vhigh3 = np.fmin(rule6,rule7)
binding_rule_Vhigh4 = np.fmin(rule9,rule10)
binding_rule_Vhigh5 = np.fmin(rule12,rule13)
binding_rule_Vhigh6 = np.fmin(rule15,rule16)
binding_rule_Vhigh7 = np.fmin(rule18,rule19)
binding_rule_Vhigh8 = np.fmin(rule21,rule22)
binding_rule_Vhigh9 = np.fmin(rule24,rule25)
binding_rule_Vhigh10 = np.fmin(rule27,rule28)
binding_rule_Vhigh11 = np.fmin(rule30,rule31)
binding_rule_Vhigh12 = np.fmin(rule34,rule38)
binding_rule_Vhigh13 = np.fmin(rule42,rule46)
binding_rule_Vhigh14 = np.fmin(rule47,rule50)
binding_rule_Vhigh15 = np.fmin(rule54,rule62)
binding_rule_Vhigh16 = np.fmin(rule66,rule113)
binding_rule_Vhigh17 = np.fmin(rule118,rule163)
binding_rule_Vhigh18 = np.fmin(rule168,rule188)
binding_rule_Vhigh19 = np.fmin(rule193,rule218)

binded_binding_rule_Vhigh1 = np.fmin(binding_rule_Vhigh1,binding_rule_Vhigh2)
binded_binding_rule_Vhigh2 = np.fmin(binding_rule_Vhigh3,binding_rule_Vhigh4)
binded_binding_rule_Vhigh3 = np.fmin(binding_rule_Vhigh5,binding_rule_Vhigh6)
binded_binding_rule_Vhigh4 = np.fmin(binding_rule_Vhigh7,binding_rule_Vhigh8)
binded_binding_rule_Vhigh5 = np.fmin(binding_rule_Vhigh9,binding_rule_Vhigh10)
binded_binding_rule_Vhigh6 = np.fmin(binding_rule_Vhigh11,binding_rule_Vhigh12)
binded_binding_rule_Vhigh7 = np.fmin(binding_rule_Vhigh13,binding_rule_Vhigh14)
binded_binding_rule_Vhigh8 = np.fmin(binding_rule_Vhigh15,binding_rule_Vhigh16)
binded_binding_rule_Vhigh9 = np.fmin(binding_rule_Vhigh17,binding_rule_Vhigh18)

double_binded_binding_rule_Vhigh1 = np.fmin(binded_binding_rule_Vhigh1,binded_binding_rule_Vhigh2)
double_binded_binding_rule_Vhigh2 = np.fmin(binded_binding_rule_Vhigh3,binded_binding_rule_Vhigh4)
double_binded_binding_rule_Vhigh3 = np.fmin(binded_binding_rule_Vhigh5,binded_binding_rule_Vhigh6)
double_binded_binding_rule_Vhigh4 = np.fmin(binded_binding_rule_Vhigh7,binded_binding_rule_Vhigh8)
double_binded_binding_rule_Vhigh5 = np.fmin(binded_binding_rule_Vhigh9,binding_rule_Vhigh19)

triple_binded_binding_rule_Vhigh1 = np.fmin(np.fmin(double_binded_binding_rule_Vhigh1,double_binded_binding_rule_Vhigh2),double_binded_binding_rule_Vhigh5)
triple_binded_binding_rule_Vhigh2 = np.fmin(np.fmin(double_binded_binding_rule_Vhigh3,double_binded_binding_rule_Vhigh4),double_binded_binding_rule_Vhigh5)

quadruple_binded_binding_rule_Vhigh1 = np.fmin(triple_binded_binding_rule_Vhigh1,triple_binded_binding_rule_Vhigh2)

#Mhigh için

binding_rule_Mhigh1 = np.fmin(rule5,rule8)
binding_rule_Mhigh2 = np.fmin(rule11,rule14)
binding_rule_Mhigh3 = np.fmin(rule17,rule20)
binding_rule_Mhigh4 = np.fmin(rule23,rule32)
binding_rule_Mhigh5 = np.fmin(rule33,rule35)
binding_rule_Mhigh6 = np.fmin(rule36,rule39)
binding_rule_Mhigh7 = np.fmin(rule48,rule51)
binding_rule_Mhigh8 = np.fmin(rule52,rule55)
binding_rule_Mhigh9 = np.fmin(rule58,rule59)
binding_rule_Mhigh10 = np.fmin(rule63,rule67)
binding_rule_Mhigh11 = np.fmin(rule70,rule74)
binding_rule_Mhigh12 = np.fmin(rule78,rule79)
binding_rule_Mhigh13 = np.fmin(rule82,rule83)
binding_rule_Mhigh14 = np.fmin(rule107,rule108)
binding_rule_Mhigh15 = np.fmin(rule112,rule117)
binding_rule_Mhigh16 = np.fmin(rule132,rule133)
binding_rule_Mhigh17 = np.fmin(rule137,rule138)
binding_rule_Mhigh18 = np.fmin(rule142,rule143)
binding_rule_Mhigh19 = np.fmin(rule153,rule157)
binding_rule_Mhigh20 = np.fmin(rule158,rule162)
binding_rule_Mhigh21 = np.fmin(rule167,rule177)
binding_rule_Mhigh22 = np.fmin(rule178,rule182)
binding_rule_Mhigh23 = np.fmin(rule183,rule187)
binding_rule_Mhigh24 = np.fmin(rule192,rule198)
binding_rule_Mhigh25 = np.fmin(rule207,rule208)
binding_rule_Mhigh26 = np.fmin(np.fmin(rule212,rule213),rule217)

binded_binding_rule_Mhigh1 = np.fmin(binding_rule_Mhigh1,binding_rule_Vhigh2)
binded_binding_rule_Mhigh2 = np.fmin(binding_rule_Mhigh3,binding_rule_Mhigh4)
binded_binding_rule_Mhigh3 = np.fmin(binding_rule_Mhigh5,binding_rule_Mhigh6)
binded_binding_rule_Mhigh4 = np.fmin(binding_rule_Mhigh7,binding_rule_Mhigh8)
binded_binding_rule_Mhigh5 = np.fmin(binding_rule_Mhigh9,binding_rule_Mhigh10)
binded_binding_rule_Mhigh6 = np.fmin(binding_rule_Mhigh11,binding_rule_Mhigh12)
binded_binding_rule_Mhigh7 = np.fmin(binding_rule_Mhigh13,binding_rule_Vhigh14)
binded_binding_rule_Mhigh8 = np.fmin(binding_rule_Mhigh15,binding_rule_Mhigh16)
binded_binding_rule_Mhigh9 = np.fmin(binding_rule_Mhigh17,binding_rule_Mhigh18)
binded_binding_rule_Mhigh10 = np.fmin(binding_rule_Mhigh19,binding_rule_Mhigh20)
binded_binding_rule_Mhigh11 = np.fmin(binding_rule_Mhigh21,binding_rule_Mhigh22)
binded_binding_rule_Mhigh12 = np.fmin(binding_rule_Mhigh23,binding_rule_Mhigh24)
binded_binding_rule_Mhigh13 = np.fmin(binding_rule_Mhigh25,binding_rule_Mhigh26)

double_binded_binding_rule_Mhigh1 = np.fmin(binded_binding_rule_Mhigh1,binded_binding_rule_Mhigh2)
double_binded_binding_rule_Mhigh2 = np.fmin(binded_binding_rule_Mhigh3,binded_binding_rule_Mhigh4)
double_binded_binding_rule_Mhigh3 = np.fmin(binded_binding_rule_Mhigh5,binded_binding_rule_Mhigh6)
double_binded_binding_rule_Mhigh4 = np.fmin(binded_binding_rule_Mhigh7,binded_binding_rule_Mhigh8)
double_binded_binding_rule_Mhigh5 = np.fmin(binded_binding_rule_Mhigh9,binded_binding_rule_Mhigh10)
double_binded_binding_rule_Mhigh6 = np.fmin(np.fmin(binded_binding_rule_Mhigh11,binded_binding_rule_Mhigh12),binded_binding_rule_Mhigh13)

triple_binded_binding_rule_Mhigh1 = np.fmin(double_binded_binding_rule_Mhigh1,double_binded_binding_rule_Mhigh2)
triple_binded_binding_rule_Mhigh2 = np.fmin(double_binded_binding_rule_Mhigh3,double_binded_binding_rule_Mhigh4)
triple_binded_binding_rule_Mhigh3 = np.fmin(double_binded_binding_rule_Mhigh5,double_binded_binding_rule_Mhigh6)

quadruple_binded_binding_rule_Mhigh1 = np.fmin(np.fmin(triple_binded_binding_rule_Mhigh1,triple_binded_binding_rule_Mhigh2),triple_binded_binding_rule_Mhigh3)

#AVE

binding_rule_AVE1 = np.fmin(rule29,rule37)
binding_rule_AVE2 = np.fmin(rule40,rule43)
binding_rule_AVE3 = np.fmin(rule44,rule49)
binding_rule_AVE4 = np.fmin(rule53,rule56)
binding_rule_AVE5 = np.fmin(rule57,rule60)
binding_rule_AVE6 = np.fmin(rule64,rule65)
binding_rule_AVE7 = np.fmin(rule68,rule69)
binding_rule_AVE8 = np.fmin(rule71,rule72)
binding_rule_AVE9 = np.fmin(rule75,rule76)
binding_rule_AVE10 = np.fmin(rule80,rule84)
binding_rule_AVE11 = np.fmin(rule86,rule87)
binding_rule_AVE12 = np.fmin(rule88,rule90)
binding_rule_AVE13 = np.fmin(rule98,rule102)
binding_rule_AVE14 = np.fmin(rule103,rule106)
binding_rule_AVE15 = np.fmin(rule111,rule116)
binding_rule_AVE16 = np.fmin(rule127,rule128)
binding_rule_AVE17 = np.fmin(rule131,rule136)
binding_rule_AVE18 = np.fmin(rule141,rule147)
binding_rule_AVE19 = np.fmin(rule148,rule152)
binding_rule_AVE20 = np.fmin(rule156,rule161)
binding_rule_AVE21 = np.fmin(rule166,rule172)
binding_rule_AVE22 = np.fmin(rule173,rule176)
binding_rule_AVE23 = np.fmin(rule181,rule186)
binding_rule_AVE24 = np.fmin(rule191,rule196)
binding_rule_AVE25 = np.fmin(rule197,rule203)
binding_rule_AVE26 = np.fmin(np.fmin(rule206,rule211),rule216)

binded_binding_rule_AVE1 = np.fmin(binding_rule_AVE1,binding_rule_AVE2)
binded_binding_rule_AVE2 = np.fmin(binding_rule_AVE3,binding_rule_AVE4)
binded_binding_rule_AVE3 = np.fmin(binding_rule_AVE5,binding_rule_AVE6)
binded_binding_rule_AVE4 = np.fmin(binding_rule_AVE7,binding_rule_AVE8)
binded_binding_rule_AVE5 = np.fmin(binding_rule_AVE9,binding_rule_AVE10)
binded_binding_rule_AVE6 = np.fmin(binding_rule_AVE11,binding_rule_AVE12)
binded_binding_rule_AVE7 = np.fmin(binding_rule_AVE13,binding_rule_AVE14)
binded_binding_rule_AVE8 = np.fmin(binding_rule_AVE15,binding_rule_AVE16)
binded_binding_rule_AVE9 = np.fmin(binding_rule_AVE17,binding_rule_AVE18)
binded_binding_rule_AVE10 = np.fmin(binding_rule_AVE19,binding_rule_AVE20)
binded_binding_rule_AVE11 = np.fmin(binding_rule_AVE21,binding_rule_AVE22)
binded_binding_rule_AVE12 = np.fmin(binding_rule_AVE23,binding_rule_AVE24)
binded_binding_rule_AVE13 = np.fmin(binding_rule_AVE25,binding_rule_AVE26)

double_binded_binding_rule_AVE1 = np.fmin(binded_binding_rule_AVE1,binded_binding_rule_AVE2)
double_binded_binding_rule_AVE2 = np.fmin(binded_binding_rule_AVE3,binded_binding_rule_AVE4)
double_binded_binding_rule_AVE3 = np.fmin(binded_binding_rule_AVE5,binded_binding_rule_AVE6)
double_binded_binding_rule_AVE4 = np.fmin(binded_binding_rule_AVE7,binded_binding_rule_AVE8)
double_binded_binding_rule_AVE5 = np.fmin(binded_binding_rule_AVE9,binded_binding_rule_AVE10)
double_binded_binding_rule_AVE6 = np.fmin(np.fmin(binded_binding_rule_AVE11,binded_binding_rule_AVE12),binded_binding_rule_AVE13)

triple_binded_binding_rule_AVE1 = np.fmin(double_binded_binding_rule_AVE1,double_binded_binding_rule_AVE2)
triple_binded_binding_rule_AVE2 = np.fmin(double_binded_binding_rule_AVE3,double_binded_binding_rule_AVE4)
triple_binded_binding_rule_AVE3 = np.fmin(double_binded_binding_rule_AVE5,double_binded_binding_rule_AVE6)

quadruple_binded_binding_rule_AVE1 = np.fmin(np.fmin(triple_binded_binding_rule_AVE1,triple_binded_binding_rule_AVE2),triple_binded_binding_rule_AVE3)

#mlow

binding_rule_MLow1 = np.fmin(rule41,rule45)
binding_rule_MLow2 = np.fmin(rule61,rule73)
binding_rule_MLow3 = np.fmin(rule77,rule81)
binding_rule_MLow4 = np.fmin(rule85,rule89)
binding_rule_MLow5 = np.fmin(rule91,rule92)
binding_rule_MLow6 = np.fmin(rule93,rule96)
binding_rule_MLow7 = np.fmin(rule97,rule101)
binding_rule_MLow8 = np.fmin(rule104,rule105)
binding_rule_MLow9 = np.fmin(rule109,rule110)
binding_rule_MLow10 = np.fmin(rule115,rule121)
binding_rule_MLow11 = np.fmin(rule122,rule123)
binding_rule_MLow12 = np.fmin(rule125,rule126)
binding_rule_MLow13 = np.fmin(rule130,rule135)
binding_rule_MLow14 = np.fmin(rule140,rule146)
binding_rule_MLow15 = np.fmin(rule151,rule155)
binding_rule_MLow16 = np.fmin(rule160,rule165)
binding_rule_MLow17 = np.fmin(rule185,rule190)
binding_rule_MLow18 = np.fmin(rule201,rule202)
binding_rule_MLow19 = np.fmin(np.fmin(rule205,rule210),rule215)

binded_binding_rule_MLow1 = np.fmin(binding_rule_MLow1,binding_rule_MLow2)
binded_binding_rule_MLow2 = np.fmin(binding_rule_MLow3,binding_rule_MLow4)
binded_binding_rule_MLow3 = np.fmin(binding_rule_MLow5,binding_rule_MLow6)
binded_binding_rule_MLow4 = np.fmin(binding_rule_MLow7,binding_rule_MLow8)
binded_binding_rule_MLow5 = np.fmin(binding_rule_MLow9,binding_rule_MLow10)
binded_binding_rule_MLow6 = np.fmin(binding_rule_MLow11,binding_rule_MLow12)
binded_binding_rule_MLow7 = np.fmin(binding_rule_MLow13,binding_rule_MLow14)
binded_binding_rule_MLow8 = np.fmin(binding_rule_MLow15,binding_rule_MLow16)
binded_binding_rule_MLow9 = np.fmin(np.fmin(binding_rule_MLow17,binding_rule_MLow18),binding_rule_MLow19)

double_binded_binding_rule_MLow1 = np.fmin(binded_binding_rule_MLow1,binded_binding_rule_MLow2)
double_binded_binding_rule_MLow2 = np.fmin(binded_binding_rule_MLow3,binded_binding_rule_MLow4)
double_binded_binding_rule_MLow3 = np.fmin(binded_binding_rule_MLow5,binded_binding_rule_MLow6)
double_binded_binding_rule_MLow4 = np.fmin(np.fmin(binded_binding_rule_MLow7,binded_binding_rule_MLow8),binded_binding_rule_MLow9)

triple_binded_binding_rule_MLow1 = np.fmin(double_binded_binding_rule_MLow1,double_binded_binding_rule_MLow2)
triple_binded_binding_rule_MLow2 = np.fmin(double_binded_binding_rule_MLow3,double_binded_binding_rule_MLow4)

quadruple_binded_binding_rule_MLow1 = np.fmin(triple_binded_binding_rule_MLow1,triple_binded_binding_rule_MLow2)

#Vlow

binding_rule_VLow1 = np.fmin(rule94,rule95)
binding_rule_VLow2 = np.fmin(rule99,rule100)
binding_rule_VLow3 = np.fmin(rule114,rule119)
binding_rule_VLow4 = np.fmin(rule120,rule124)
binding_rule_VLow5 = np.fmin(rule129,rule134)
binding_rule_VLow6 = np.fmin(rule139,rule144)
binding_rule_VLow7 = np.fmin(rule145,rule149)
binding_rule_VLow8 = np.fmin(rule150,rule154)
binding_rule_VLow9 = np.fmin(rule159,rule164)
binding_rule_VLow10 = np.fmin(rule169,rule170)
binding_rule_VLow11 = np.fmin(rule171,rule174)
binding_rule_VLow12 = np.fmin(rule175,rule179)
binding_rule_VLow13 = np.fmin(rule180,rule184)
binding_rule_VLow14 = np.fmin(rule189,rule194)
binding_rule_VLow15 = np.fmin(rule195,rule199)
binding_rule_VLow16 = np.fmin(rule200,rule204)
binding_rule_VLow17 = np.fmin(rule209,rule214)

binded_binding_rule_VLow1 = np.fmin(binding_rule_VLow1,binding_rule_VLow2)
binded_binding_rule_VLow2 = np.fmin(binding_rule_VLow3,binding_rule_VLow4)
binded_binding_rule_VLow3 = np.fmin(binding_rule_VLow5,binding_rule_VLow6)
binded_binding_rule_VLow4 = np.fmin(binding_rule_VLow7,binding_rule_VLow8)
binded_binding_rule_VLow5 = np.fmin(binding_rule_VLow9,binding_rule_VLow10)
binded_binding_rule_VLow6 = np.fmin(binding_rule_VLow11,binding_rule_VLow12)
binded_binding_rule_VLow7 = np.fmin(binding_rule_VLow13,binding_rule_VLow14)
binded_binding_rule_VLow8 = np.fmin(np.fmin(binding_rule_VLow15,binding_rule_VLow16),binding_rule_VLow17)

double_binded_binding_rule_VLow1 = np.fmin(binded_binding_rule_VLow1,binded_binding_rule_VLow2)
double_binded_binding_rule_VLow2 = np.fmin(binded_binding_rule_VLow3,binded_binding_rule_VLow4)
double_binded_binding_rule_VLow3 = np.fmin(binded_binding_rule_VLow5,binded_binding_rule_VLow6)
double_binded_binding_rule_VLow4 = np.fmin(binded_binding_rule_VLow7,binded_binding_rule_VLow8)

triple_binded_binding_rule_VLow1 = np.fmin(double_binded_binding_rule_VLow1,double_binded_binding_rule_VLow2)
triple_binded_binding_rule_VLow2 = np.fmin(double_binded_binding_rule_VLow3,double_binded_binding_rule_VLow4)

quadruple_binded_binding_rule_VLow1 = np.fmin(triple_binded_binding_rule_VLow1,triple_binded_binding_rule_VLow2)



active_rule2 = np.fmax(PartialRatio_fit_AVE,TokenRatio_fit_AVE)
active_rule3 = np.fmax(TokenSetRatio_fit_AVE,TokenRatio_fit_MLow)
active_rule4 = np.fmax(TokenRatio_fit_VLow,TokenSetRatio_fit_VLow)

benzerlik_active_Vhigh = np.fmin(quadruple_binded_binding_rule_Vhigh1,BenzerlikRatio_VHigh)
benzerlik_active_Mhigh = np.fmin(quadruple_binded_binding_rule_Mhigh1,BenzerlikRatio_MHigh)
benzerlik_active_AVE = np.fmin(quadruple_binded_binding_rule_AVE1,BenzerlikRatio_AVE)
benzerlik_active_MLow = np.fmin(quadruple_binded_binding_rule_MLow1,BenzerlikRatio_MLow)
benzerlik_active_VLow = np.fmin(quadruple_binded_binding_rule_VLow1,BenzerlikRatio_VLow)

Benzerlik0 = np.zeros_like(x_Benzerlikratio)

fig , ax0 = plt.subplots(figsize=(8,5))

ax0.fill_between(x_Benzerlikratio,Benzerlik0,benzerlik_active_Vhigh, facecolor = "r", alpha = 0.7)
ax0.plot(x_Benzerlikratio, BenzerlikRatio_VHigh, 'b', linewidth=0.5, linestyle='--', )

ax0.fill_between(x_Benzerlikratio,Benzerlik0,benzerlik_active_Mhigh, facecolor = "g", alpha = 0.7)
ax0.plot(x_Benzerlikratio, BenzerlikRatio_MHigh, 'b', linewidth=0.5, linestyle='--', )

ax0.fill_between(x_Benzerlikratio,Benzerlik0,benzerlik_active_AVE, facecolor = "c", alpha = 0.7)
ax0.plot(x_Benzerlikratio, BenzerlikRatio_AVE, 'b', linewidth=0.5, linestyle='--', )

ax0.fill_between(x_Benzerlikratio,Benzerlik0,benzerlik_active_MLow, facecolor = "m", alpha = 0.7)
ax0.plot(x_Benzerlikratio, BenzerlikRatio_MLow, 'b', linewidth=0.5, linestyle='--', )

ax0.fill_between(x_Benzerlikratio,Benzerlik0,benzerlik_active_VLow, facecolor = "y", alpha = 0.7)
ax0.plot(x_Benzerlikratio, BenzerlikRatio_VLow, 'b', linewidth=0.5, linestyle='--', )

for ax in (ax0,):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.get_xaxis().tick_bottom()
    ax.get_yaxis().tick_left()

plt.tight_layout()

aggregated = np.fmax(np.fmax(np.fmax(np.fmax(benzerlik_active_Vhigh,benzerlik_active_Mhigh),benzerlik_active_AVE),benzerlik_active_MLow),benzerlik_active_VLow)

FullBenzerlikRatio = skfuzzy.defuzz(x_Benzerlikratio, aggregated, 'centroid')

benzerlik_activation = skfuzzy.interp_membership(x_Benzerlikratio, aggregated, FullBenzerlikRatio)

ax0.plot(x_Benzerlikratio, BenzerlikRatio_VHigh, 'r', linewidth=0.5, linestyle='--', )
ax0.plot(x_Benzerlikratio, BenzerlikRatio_MHigh, 'g', linewidth=0.5, linestyle='--', )
ax0.plot(x_Benzerlikratio, BenzerlikRatio_AVE, 'c', linewidth=0.5, linestyle='--', )
ax0.plot(x_Benzerlikratio, BenzerlikRatio_MLow, 'm', linewidth=0.5, linestyle='--', )
ax0.plot(x_Benzerlikratio, BenzerlikRatio_VLow, 'y', linewidth=0.5, linestyle='--', )


ax0.fill_between(x_Benzerlikratio, Benzerlik0, aggregated, facecolor='Orange', alpha=0.7)
ax0.plot([FullBenzerlikRatio, FullBenzerlikRatio], [0, benzerlik_activation], 'k', linewidth=1.5, alpha=0.9)
ax0.set_title('Aggregated membership and result')

for ax in (ax0,):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.get_xaxis().tick_bottom()
    ax.get_yaxis().tick_left()

Crispset = sum(benzerlik_active_VLow)+sum(benzerlik_active_MLow)+sum(benzerlik_active_AVE)+sum(benzerlik_active_Mhigh)+sum(benzerlik_active_Vhigh)

print("Crisp Setimiz :  ",Crispset)
plt.tight_layout()

plt.show()
